version: "3"
volumes:
  vl:
    driver: "local"
networks:
  share_network:
# Blank Line
services:
  backend:
    container_name: "backend"
    build:
      context: ./
      dockerfile: ./.devcontainer/backend/Dockerfile
    ports:
      - 3010:3010
    environment:
      - HOST=0.0.0.0
      - PORT=3010
    volumes:
      - ./:/workspace:cached
      - ./vscode:/vscode:cached
      - /workspace/backend/node_modules
    tty: true
    networks:
      - share_network
